import {ILaunches} from '@store/modules/api/interface';

export const launchesItemMock: ILaunches = {
  crew: null,
  details: 'Engine failure at 33 seconds and loss of vehicle',
  flight_number: 1,
  is_tentative: false,
  launch_date_local: '2006-03-25T10:30:00+12:00',
  launch_date_unix: 1143239400,
  launch_date_utc: '2006-03-24T22:30:00.000Z',
  launch_failure_details: {
    altitude: null,
    reason: 'merlin engine failure',
    time: 33,
  },
  launch_site: {
    site_id: 'kwajalein_atoll',
    site_name: 'Kwajalein Atoll',
    site_name_long: 'Kwajalein Atoll Omelek Island',
  },
  launch_success: false,
  launch_window: 0,
  launch_year: '2006',
  links: {
    article_link:
      'https://www.space.com/2196-spacex-inaugural-falcon-1-rocket-lost-launch.html',
    flickr_images: [],
    mission_patch: 'https://images2.imgbox.com/40/e3/GypSkayF_o.png',
    mission_patch_small: 'https://images2.imgbox.com/3c/0e/T8iJcSN3_o.png',
    presskit: null,
    reddit_campaign: null,
    reddit_launch: null,
    reddit_media: null,
    reddit_recovery: null,
    video_link: 'https://www.youtube.com/watch?v=0a_00nJ_Y88',
    wikipedia: 'https://en.wikipedia.org/wiki/DemoSat',
    youtube_id: '0a_00nJ_Y88',
  },
  mission_id: [],
  mission_name: 'FalconSat',
  rocket: {
    fairings: {
      recovered: false,
      recovery_attempt: false,
      reused: false,
      ship: null,
    },
    first_stage: {cores: [Array]},
    rocket_id: 'falcon1',
    rocket_name: 'Falcon 1',
    rocket_type: 'Merlin A',
    second_stage: {block: 1, payloads: [Array]},
  },
  ships: [],
  static_fire_date_unix: 1142553600,
  static_fire_date_utc: '2006-03-17T00:00:00.000Z',
  tbd: false,
  telemetry: {flight_club: null},
  tentative_max_precision: 'hour',
  timeline: {webcast_liftoff: 54},
  upcoming: false,
};
